/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import conexaoBD.Conexao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Vs.1 com a as tabelas separadas cliente e endereço
 * @author AQUI TEM
 */
public class Filtro extends javax.swing.JFrame {
    Conexao conexao = new Conexao();
    DefaultListModel modelo;
    
    /**
     * Creates new form Filtro
     */
    public Filtro() {
        initComponents();
        setLocationRelativeTo(null);
        conexao.conectar();
        ResultadoFiltro();
        FiltroEndereco();
        Lista.setVisible(false);
        modelo = new DefaultListModel();
        Lista.setModel(modelo);
        //limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jpnFundo = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        btnFiltro = new javax.swing.JButton();
        btnSaude = new javax.swing.JButton();
        btnAdvogado = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnImpressao = new javax.swing.JButton();
        btnOutros = new javax.swing.JButton();
        lblCodCliente = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblApelido = new javax.swing.JLabel();
        txtApelido = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblWhatssap = new javax.swing.JLabel();
        txtWhatssap = new javax.swing.JTextField();
        lblDataNasc = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        lblNomeMae = new javax.swing.JLabel();
        txtNomeMae = new javax.swing.JTextField();
        lblCartaoSUS = new javax.swing.JLabel();
        txtCartaoSus = new javax.swing.JTextField();
        lblTituloEleitoral = new javax.swing.JLabel();
        txtTituloEleitoral = new javax.swing.JTextField();
        lblNomePai = new javax.swing.JLabel();
        txtNomePai = new javax.swing.JTextField();
        lblSecaoEleitoral = new javax.swing.JLabel();
        txtSecaoEleitoral = new javax.swing.JTextField();
        txtZonaEleitoral = new javax.swing.JTextField();
        lblZonaEleitoral = new javax.swing.JLabel();
        lblDataCadastro = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JTextField();
        lblOBS = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOBS = new javax.swing.JTextArea();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        txtUF = new javax.swing.JTextField();
        btnSalvarCadastro = new javax.swing.JButton();
        btnSaida1 = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        txtPesquisarNome = new javax.swing.JTextField();
        Lista = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Filtro");

        jLayeredPane2.setBackground(new java.awt.Color(140, 197, 61));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane2.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(0, 115, 190));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnFundo.setBackground(new java.awt.Color(140, 197, 61));

        btnHome.setBackground(new java.awt.Color(140, 197, 61));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home2.png"))); // NOI18N
        btnHome.setToolTipText("Home");
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnCadastro.setBackground(new java.awt.Color(140, 197, 61));
        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cadastro.png"))); // NOI18N
        btnCadastro.setToolTipText("Cadastrar");
        btnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendario.png"))); // NOI18N
        btnAgenda.setToolTipText("Agenda");
        btnAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });

        btnFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/filtro.png"))); // NOI18N
        btnFiltro.setToolTipText("Filtrar");
        btnFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });

        btnSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/saude (2).png"))); // NOI18N
        btnSaude.setToolTipText("Saúde");
        btnSaude.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAdvogado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/advogados (2).png"))); // NOI18N
        btnAdvogado.setToolTipText("Advogados");
        btnAdvogado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/relatorio.png"))); // NOI18N
        btnRelatorio.setToolTipText("Relatório");
        btnRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        btnImpressao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/impressão.png"))); // NOI18N
        btnImpressao.setToolTipText("Impressão");
        btnImpressao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnOutros.setBackground(new java.awt.Color(140, 197, 61));
        btnOutros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        btnOutros.setToolTipText("Outras Solicitações");
        btnOutros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnFundoLayout = new javax.swing.GroupLayout(jpnFundo);
        jpnFundo.setLayout(jpnFundoLayout);
        jpnFundoLayout.setHorizontalGroup(
            jpnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnFundoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jpnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnFundoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnFundoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnImpressao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSaude, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnFundoLayout.setVerticalGroup(
            jpnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaude, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImpressao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnOutros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jpnFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 490));

        lblCodCliente.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCodCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCodCliente.setText("Cod. Cliente:");
        jPanel1.add(lblCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        txtCodCliente.setEditable(false);
        txtCodCliente.setToolTipText("Código");
        txtCodCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, 30));

        lblStatus.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStatus.setText("Status:");
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 60, -1));

        txtStatus.setToolTipText("Status");
        txtStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 80, -1));

        lblNomeCliente.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeCliente.setText("Nome:");
        jPanel1.add(lblNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 90, -1));

        txtNomeCliente.setToolTipText("Informe o nome do Cliente");
        txtNomeCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 400, 30));

        lblApelido.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblApelido.setForeground(new java.awt.Color(255, 255, 255));
        lblApelido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblApelido.setText("Apelido:");
        jPanel1.add(lblApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 80, -1));

        txtApelido.setToolTipText("Como é Conhecido");
        txtApelido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApelidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 90, -1));

        lblCelular.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(255, 255, 255));
        lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCelular.setText("Celular:");
        jPanel1.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, -1));

        txtCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 30));

        lblWhatssap.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblWhatssap.setForeground(new java.awt.Color(255, 255, 255));
        lblWhatssap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWhatssap.setText("Whatssap:");
        jPanel1.add(lblWhatssap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 120, -1));

        txtWhatssap.setToolTipText("Informe o Whatssap");
        txtWhatssap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtWhatssap, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, 30));

        lblDataNasc.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblDataNasc.setForeground(new java.awt.Color(255, 255, 255));
        lblDataNasc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataNasc.setText("Data Nascimento");
        jPanel1.add(lblDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        txtDataNasc.setToolTipText("A data de Nascimento");
        txtDataNasc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascActionPerformed(evt);
            }
        });
        jPanel1.add(txtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 110, 30));

        lblEstadoCivil.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblEstadoCivil.setText("Estado Civil");
        jPanel1.add(lblEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));
        jPanel1.add(txtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 80, -1));

        lblCPF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCPF.setText("CPF:");
        jPanel1.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 90, -1));

        txtCPF.setToolTipText("O CPF");
        txtCPF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 110, 30));

        lblRG.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblRG.setForeground(new java.awt.Color(255, 255, 255));
        lblRG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRG.setText("RG:");
        jPanel1.add(lblRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 60, 20));

        txtRG.setToolTipText("O Doc Identidade");
        txtRG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRGActionPerformed(evt);
            }
        });
        jPanel1.add(txtRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 90, 30));

        lblNomeMae.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblNomeMae.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeMae.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeMae.setText("Nome Mãe:");
        jPanel1.add(lblNomeMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, -1));

        txtNomeMae.setToolTipText("Filiação Nome da Mãe");
        txtNomeMae.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNomeMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMaeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomeMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 400, 30));

        lblCartaoSUS.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCartaoSUS.setForeground(new java.awt.Color(255, 255, 255));
        lblCartaoSUS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCartaoSUS.setText("Cartão do SUS");
        jPanel1.add(lblCartaoSUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 120, -1));

        txtCartaoSus.setToolTipText("N° do Cartão Sus");
        txtCartaoSus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCartaoSus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCartaoSusActionPerformed(evt);
            }
        });
        jPanel1.add(txtCartaoSus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 130, 30));

        lblTituloEleitoral.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblTituloEleitoral.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloEleitoral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloEleitoral.setText("Titulo Eleitoral:");
        jPanel1.add(lblTituloEleitoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 120, -1));

        txtTituloEleitoral.setToolTipText("N° do Titulo");
        txtTituloEleitoral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTituloEleitoral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloEleitoralActionPerformed(evt);
            }
        });
        jPanel1.add(txtTituloEleitoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 130, 30));

        lblNomePai.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblNomePai.setForeground(new java.awt.Color(255, 255, 255));
        lblNomePai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomePai.setText("Nome Pai:");
        jPanel1.add(lblNomePai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, -1));

        txtNomePai.setToolTipText("Filiação Nome do Pai");
        txtNomePai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNomePai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePaiActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomePai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 400, 30));

        lblSecaoEleitoral.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblSecaoEleitoral.setForeground(new java.awt.Color(255, 255, 255));
        lblSecaoEleitoral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSecaoEleitoral.setText("Seção Eleitoral");
        jPanel1.add(lblSecaoEleitoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 120, -1));

        txtSecaoEleitoral.setToolTipText("N° Sessão de Votação");
        txtSecaoEleitoral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtSecaoEleitoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 130, 30));

        txtZonaEleitoral.setToolTipText("N° Zona Eleitoral");
        txtZonaEleitoral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtZonaEleitoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 130, 30));

        lblZonaEleitoral.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblZonaEleitoral.setForeground(new java.awt.Color(255, 255, 255));
        lblZonaEleitoral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblZonaEleitoral.setText("Zona Eleitoral:");
        jPanel1.add(lblZonaEleitoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 130, -1));

        lblDataCadastro.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblDataCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblDataCadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataCadastro.setText("Data do Cadastro:");
        jPanel1.add(lblDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, -1));

        txtDataCadastro.setToolTipText("Data do Cadastro");
        txtDataCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(txtDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 120, 30));

        lblOBS.setForeground(new java.awt.Color(255, 255, 255));
        lblOBS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOBS.setText("OBS:");
        jPanel1.add(lblOBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 50, -1));

        txtOBS.setColumns(20);
        txtOBS.setRows(5);
        txtOBS.setToolTipText("Campo para Observações");
        jScrollPane1.setViewportView(txtOBS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 480, 80));

        lblEndereco.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco.setText("Endereço: Av, Rua, Travessa");
        jPanel1.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 240, -1));

        txtEndereco.setToolTipText("Informe seu Endereço");
        txtEndereco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 590, 30));

        lblBairro.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(255, 255, 255));
        lblBairro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBairro.setText("Bairro:");
        jPanel1.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 100, -1));

        txtBairro.setToolTipText("O Bairro");
        txtBairro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 250, 30));

        lblComplemento.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblComplemento.setForeground(new java.awt.Color(255, 255, 255));
        lblComplemento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComplemento.setText("Complemento: Apt, Casa, Sítio,  Etapa");
        jPanel1.add(lblComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 230, -1));

        txtComplemento.setToolTipText("Complemento");
        txtComplemento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });
        jPanel1.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 250, 30));

        lblCidade.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(255, 255, 255));
        lblCidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCidade.setText("Cidade:");
        jPanel1.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 100, -1));

        txtCidade.setToolTipText("A Cidade");
        txtCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 140, 30));

        lblCEP.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCEP.setForeground(new java.awt.Color(255, 255, 255));
        lblCEP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCEP.setText("CEP:");
        jPanel1.add(lblCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 100, -1));

        txtCEP.setToolTipText("Seu Cep");
        txtCEP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });
        jPanel1.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 140, 30));

        lblUF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblUF.setForeground(new java.awt.Color(255, 255, 255));
        lblUF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUF.setText("UF:");
        jPanel1.add(lblUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 40, -1));

        txtUF.setToolTipText("O Estado");
        txtUF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUFActionPerformed(evt);
            }
        });
        jPanel1.add(txtUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 50, 30));

        btnSalvarCadastro.setBackground(new java.awt.Color(0, 115, 190));
        btnSalvarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/diskete.png"))); // NOI18N
        btnSalvarCadastro.setToolTipText("Salvando as Informações");
        btnSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 60, 40));

        btnSaida1.setBackground(new java.awt.Color(0, 115, 190));
        btnSaida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/saida.png"))); // NOI18N
        btnSaida1.setToolTipText("Saindo do Cadastro");
        btnSaida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaida1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 50, 40));

        btnAnterior.setBackground(new java.awt.Color(0, 115, 190));
        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/anterior.png"))); // NOI18N
        btnAnterior.setToolTipText("Cadastro Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 50, 40));

        btnProximo.setBackground(new java.awt.Color(0, 115, 190));
        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/proximo.png"))); // NOI18N
        btnProximo.setToolTipText("Proximo Cadastro");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        jPanel1.add(btnProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 50, 40));

        txtPesquisarNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarNomeActionPerformed(evt);
            }
        });
        txtPesquisarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarNomeKeyPressed(evt);
            }
        });

        Lista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtPesquisarNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Lista, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(txtPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here: Ir para o Menu
        Menu telaMenu = new Menu();
        telaMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:Tela Cadastra
        Cadastro telaCadastro = new Cadastro();
        telaCadastro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        // TODO add your handling code here: ir para tela Filtro
        Filtro telaFiltro = new Filtro();
        telaFiltro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFiltroActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutrosActionPerformed
        // TODO add your handling code here: ir para outros
        Outros telaOutros = new Outros();
        telaOutros.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnOutrosActionPerformed

    private void txtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCodClienteActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteActionPerformed

    private void txtApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApelidoActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRGActionPerformed

    private void txtNomeMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMaeActionPerformed

    private void txtCartaoSusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCartaoSusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCartaoSusActionPerformed

    private void txtTituloEleitoralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloEleitoralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloEleitoralActionPerformed

    private void txtNomePaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePaiActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUFActionPerformed

    private void btnSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroActionPerformed
        // TODO add your handling code here: Salvar no banco de dados
        Conexao conn = new Conexao();

        try {
            // 1. Obter os dados dos componentes do formulário
            String codCliente = txtCodCliente.getText().trim();
            String status = txtStatus.getText().trim();
            String nomeCliente = txtNomeCliente.getText().trim();
            String apelido = txtApelido.getText().trim();
            String celular = txtCelular.getText().trim();
            String whatssap = txtWhatssap.getText().trim();
            String dataNasc = txtDataNasc.getText().trim();
            String estadoCivil = txtEstadoCivil.getText().trim();
            String nomeMae =  txtNomeMae.getText().trim();
            String nomePai = txtNomePai.getText().trim();
            String cpf = txtCPF.getText().trim();
            String rg = txtRG.getText().trim();
            String cartaoSUS = txtCartaoSus.getText().trim();
            String tituloEleitoral = txtTituloEleitoral.getText().trim();
            String secaoEleitora = txtSecaoEleitoral.getText().trim();
            String zonaEleitoral = txtZonaEleitoral.getText().trim();
            String dataCadastro = txtDataCadastro.getText().trim();
            String endereco = txtEndereco.getText().trim();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao salvar");
        }
    }//GEN-LAST:event_btnSalvarCadastroActionPerformed

    private void btnSaida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaida1ActionPerformed
        // TODO add your handling code here:Sair do Sistema
        Menu telaMenu = new Menu();
        telaMenu.setVisible(true);
        dispose();dispose();
    }//GEN-LAST:event_btnSaida1ActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here: volta um na tabela
/*
// Obtém o índice da linha selecionada atualmente na tabela
    int linhaSelecionada = jTableClientes.getSelectedRow();

    // Verifica se há alguma linha selecionada
    if (linhaSelecionada == -1) {
        // Se nenhuma linha estiver selecionada, seleciona a última linha por padrão
        JOptionPane.showMessageDialog(this, "Nenhuma linha está selecionada. Selecione uma linha primeiro.", "Aviso", JOptionPane.WARNING_MESSAGE);
    } else if (linhaSelecionada > 0) {
        // Se a linha selecionada não for a primeira, seleciona a linha anterior
        jTableClientes.setRowSelectionInterval(linhaSelecionada - 1, linhaSelecionada - 1);
    } else {
        // Caso esteja na primeira linha, exibe um aviso
        JOptionPane.showMessageDialog(this, "Você já está na primeira linha.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    } */
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        // TODO add your handling code here: Sair do Sistema
        
    }//GEN-LAST:event_btnProximoActionPerformed

    private void txtPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarNomeActionPerformed
        // TODO add your handling code here: filtra cliente
        if (!txtPesquisarNome.getText().trim().isEmpty()) {
              // filtrarClientePorNome(txtPesquisarNome.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Por favor insira um nome para pesquisar");
        }
            ResultadoFiltro();
            FiltroEndereco();
            

    }//GEN-LAST:event_txtPesquisarNomeActionPerformed

    private void txtPesquisarNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarNomeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filtro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filtro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista;
    private javax.swing.JButton btnAdvogado;
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnImpressao;
    private javax.swing.JButton btnOutros;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSaida1;
    private javax.swing.JButton btnSalvarCadastro;
    private javax.swing.JButton btnSaude;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnFundo;
    private javax.swing.JLabel lblApelido;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCartaoSUS;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodCliente;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblDataCadastro;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeMae;
    private javax.swing.JLabel lblNomePai;
    private javax.swing.JLabel lblOBS;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSecaoEleitoral;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTituloEleitoral;
    private javax.swing.JLabel lblUF;
    private javax.swing.JLabel lblWhatssap;
    private javax.swing.JLabel lblZonaEleitoral;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCartaoSus;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtDataCadastro;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtNomePai;
    private javax.swing.JTextArea txtOBS;
    private javax.swing.JTextField txtPesquisarNome;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtSecaoEleitoral;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTituloEleitoral;
    private javax.swing.JTextField txtUF;
    private javax.swing.JTextField txtWhatssap;
    private javax.swing.JTextField txtZonaEleitoral;
    // End of variables declaration//GEN-END:variables

    /*public void ListaPesquisa() {
        try{
            
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "ERRO ao Lista dados"+ erro);
        }
    }*/
        public void MostrarPesquisa(){
            ResultadoFiltro();
        }
    
    public void ResultadoFiltro(){
        Conexao conexao = new Conexao();
        // Tente conectar ao banco de dados
        if (conexao.conectar()) {
            System.out.println("Conexão com o banco de dados foi estabelecida com sucesso!");
            // Realize uma consulta simples para testar a comunicação
            try {
                Statement st = conexao.getConnection().createStatement();
                String sql = "SELECT c.Cod_cliente, c.Status_Cliente, c.nome_cliente, c.Apelido_Cliente, c.Celular, "
                    + "c.Celular_Whatsapp, c.Data_Nasc, c.Estado_Civil, c.Nome_Mae, c.Nome_Pai, c.CPF_Cliente, c.RG_Cliente, "
                    + "c.Cartao_Sus, c.Titulo_Eleitoral, c.Secao_Eleitoral, c.Zona_Eleitoral, c.Data_Cadastro, c.Observacao, "
                    + "e.id_endereco, e.logradouro, e.bairro, e.complemento, e.cidade, e.cep, e.uf "
                    + "FROM cliente c "
                    + "JOIN endereco e ON c.id_endereco = e.id_endereco";
                

                ResultSet rs = st.executeQuery("SELECT * FROM cliente");
                // Exiba os resultados
                while (rs.next()) {
                    txtCodCliente.setText(String.valueOf(rs.getInt("Cod_Cliente")));
                    txtStatus.setText(rs.getString("Status_Cliente"));
                    txtNomeCliente.setText(rs.getString("nome_cliente"));
                    txtApelido.setText(rs.getString("Apelido_Cliente"));
                    txtCelular.setText(rs.getString("Celular"));
                    txtWhatssap.setText(rs.getString("Celular_Whatsapp"));
                    txtDataNasc.setText(rs.getString("Data_Nasc"));
                    txtEstadoCivil.setText(rs.getString("Estado_Civil"));
                    txtNomeMae.setText(rs.getString("Nome_Mae"));
                    txtNomePai.setText(rs.getString("Nome_Pai"));
                    txtCPF.setText(rs.getString("CPF_Cliente"));
                    txtRG.setText(rs.getString("RG_Cliente"));
                    txtCartaoSus.setText(rs.getString("Cartao_Sus"));
                    txtTituloEleitoral.setText(rs.getString("Titulo_Eleitoral"));
                    txtSecaoEleitoral.setText(rs.getString("Secao_Eleitoral"));
                    txtZonaEleitoral.setText(rs.getString("Zona_Eleitoral"));
                    txtDataCadastro.setText(rs.getString("Data_Cadastro"));
                    txtOBS.setText(rs.getString("Observacao")); 
                } 
                
            } catch (SQLException e) {
                System.out.println("Erro ao realizar consulta: " + e.getMessage());
            } finally {
                // Desconecte do banco de dados
                conexao.desconectar();
            }
        } else {
            System.out.println("Não foi possível conectar ao banco de dados.");
                }
        //limparCampos();
}

    public void FiltroEndereco(){
        Conexao conexao = new Conexao();

        // Tente conectar ao banco de dados
        if (conexao.conectar()) {
            System.out.println("Conexão com o banco de dados foi estabelecida com sucesso!");

            // Realize uma consulta simples para testar a comunicação
            try {
                Statement st = conexao.getConnection().createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM endereco");
                // Exiba os resultados
                while (rs.next()) {
                    txtEndereco.setText(rs.getString("Logradouro"));
                    txtBairro.setText(rs.getString("Bairro"));
                    txtComplemento.setText(rs.getString("Complemento"));
                    txtCidade.setText(rs.getString("Cidade"));
                    txtCEP.setText(rs.getString("CEP"));
                    txtUF.setText(rs.getString("UF")); 
                } 

            } catch (SQLException e) {
                System.out.println("Erro ao realizar consulta: " + e.getMessage());
            } finally {
                // Desconecte do banco de dados
                conexao.desconectar();
            }
        } else {
            System.out.println("Não foi possível conectar ao banco de dados.");
        } 
        //limparCampos();
    }
    
    public void limparCampos(){
        txtCodCliente.setText("");
        txtStatus.setText("");
        txtNomeCliente.setText("");
        txtApelido.setText("");
        txtCelular.setText("");
        txtWhatssap.setText("");
        txtDataNasc.setText("");
        txtEstadoCivil.setText("");
        txtNomeMae.setText("");
        txtNomePai.setText("");
        txtCPF.setText("");
        txtRG.setText("");
        txtCartaoSus.setText("");
        txtTituloEleitoral.setText("");
        txtSecaoEleitoral.setText("");
        txtZonaEleitoral.setText("");
        txtDataCadastro.setText("");
        txtOBS.setText("");
        txtEndereco.setText("");
        txtBairro.setText("");
        txtComplemento.setText("");
        txtCidade.setText("");
        txtCEP.setText("");
        txtUF.setText("");
    }
    
}